version: "3.9"
services:
  db:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password123
    networks:
      - backend
    container_name: customer-db
  node:
    build: ./
    restart: always
    ports:
      - "80:3000"
    environment:
      - DB_USER=root
      - DB_PASSWORD=password123
      - DB_DOMAIN=customer-db
      - PORT=3000
    depends_on:
      - db
    networks:
      - backend
    container_name: customer-api
networks:
  backend:
    driver: bridge