apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: product
spec:
  selector:
    app: db_service
  clusterIP: None
  ports:
  - port: 27017 
    targetPort: 27017
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-set
  labels:
    app: db_service
  namespace: product
spec:
  selector:
    matchLabels:
      app: db_service
  serviceName: db
  replicas: 1
  template:
    metadata:
      labels:
        app: db_service
      namespace: product
    spec:
      containers:
      - name: db-container
        image: mongo 
        ports:
        - containerPort: 27017
          name: mongodb-port
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: db_user
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: db_password