apiVersion: v1
kind: Namespace
metadata:
  name: product
  labels:
    env: product
---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: product
type: Opaque
data:
  db_user: YWRtaW4=
  db_password: MWYyZDFlMmU2N2Rm