apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: customer
spec:
  selector:
    app: customer_db
  clusterIP: None
  ports:
  - port: 27017 
    targetPort: 27017
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-set
  labels:
    app: customer_db
  namespace: customer
spec:
  selector:
    matchLabels:
      app: customer_db
  serviceName: db
  replicas: 1
  template:
    metadata:
      labels:
        app: customer_db
      namespace: customer
    spec:
      containers:
      - name: db-container
        image: mongo 
        ports:
        - containerPort: 27017
          name: mongodb-port
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: db_user
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: db_password
