apiVersion: v1
kind: Namespace
metadata:
  name: customer
  labels:
    env: customer
---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: customer
type: Opaque
data:
  db_user: YWRtaW4=
  db_password: MWYyZDFlMmU2N2Rm