apiVersion: v1
kind: Namespace
metadata:
  name: shopping
  labels:
    env: shopping
---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: shopping
type: Opaque
data:
  db_user: YWRtaW4=
  db_password: MWYyZDFlMmU2N2Rm